# Generated by Django 5.1.1 on 2024-09-15 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do Autor')),
                ('criado_em', models.DateTimeField(verbose_name='criado')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Título do Livro')),
                ('criado_em', models.DateTimeField(verbose_name='criado')),
            ],
        ),
        migrations.CreateModel(
            name='LivrosDoAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_biblioteca.autor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_biblioteca.livro')),
            ],
        ),
    ]
