# Generated by Django 5.1.1 on 2024-09-15 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autor',
            table='autor',
        ),
        migrations.AlterModelTable(
            name='livro',
            table='livro',
        ),
        migrations.AlterModelTable(
            name='livrosdoautor',
            table='livros_do_autor',
        ),
    ]
