# Generated by Django 5.1.1 on 2024-09-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0002_alter_autor_table_alter_livro_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ano',
            field=models.IntegerField(default=2024, verbose_name='ano da publicação'),
        ),
    ]
