# Generated by Django 5.1.1 on 2024-09-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0003_livro_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='criado_em',
            field=models.DateField(help_text='yyyy/mm/dd', verbose_name='criado'),
        ),
    ]
