# Generated by Django 5.1.1 on 2024-09-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0004_alter_livro_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(default='Sem imagem', upload_to='livros'),
        ),
    ]
