# Generated by Django 5.1.1 on 2024-09-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0005_livro_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='capa',
        ),
    ]
