# Generated by Django 4.2.16 on 2024-09-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0007_alter_livro_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='informacaoes',
            field=models.TextField(default='', verbose_name='Informações'),
        ),
        migrations.AddField(
            model_name='livro',
            name='informacaoes',
            field=models.TextField(default='', verbose_name='Informações'),
        ),
    ]
